version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    assignees:
      - "mpwaller"
    # Specify labels for pull requests
    labels:
      - "type: library-update"
