name: qrefine
channels:
  - conda-forge
dependencies:
  # cctbx essentials
  - cctbx=2024.12
  - cctbx-base=2024.12
  - chem_data::chem_data
  - phenix-project::probe
  - phenix-project::reduce
  # essentials
  - numpy=1.26
  - python=3.11
  - networkx
  - rdkit
  - pymongo
  - ase=3.22.1
  # Calculators
  - mopac
  - xtb
  - libblas=*=*mkl
