name: qrefine-ci-mamba
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - cctbx-nightly::cctbx
  - pytorch=2.1
  - pytorch-cuda
  - cudatoolkit
  - cuda-python
  - numba
  - numpy
  - python=3.10
  - "blas=*=mkl"
  - networkx
  - pymongo
  - cxx-compiler
  - c-compiler
  - subversion
  - make
  - ase==3.17.0
  # Calculators
  - mopac
  - xtb
  - xtb-python
  - pyscf
  - torch
  - torchani=2.2
