name: qrefine
channels:
  - conda-forge
dependencies:
  # cctbx essentials
  - cctbx-nightly::cctbx
  - cctbx-nightly::cctbx-base
  - chem_data::chem_data
  - phenix-project::probe
  - phenix-project::reduce
  # essentials
  - numpy
  - python=3.10
  - networkx
  - rdkit
  - pymongo
  - ase
  # Calculators
  - mopac
  - xtb
  - libblas=*=*mkl
