channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - pytorch::pytorch=*=*cuda11*
  - pytorch::pytorch-cuda==11.8
  - cuda-python==11.8
  - conda-forge::numba
  - conda-forge::opt_einsum
  - requests
  - conda-forge::libblas=*=*mkl
  - conda-forge::cudatoolkit=11.8