channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - rdkit
  - pymongo
  - ase==3.17.0
  - xtb
  - "libblas=*=*mkl"
  # - torchani
  # - pytorch
  # - pytorch-cuda
  # - cudatoolkit
  # - cuda-python
  # - numba
